apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: frontend-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-frontend
  template:
    metadata:
      labels:
        app: node-frontend
    spec:
      containers:
      - name: node-frontend
        image: imv27/node-frontend:1.0
        env:
        - name: FLASK_SERVER_URL
          value: "http://flask-backend-service.backend-ns.svc.cluster.local:5000"
        ports:
        - containerPort: 3000
---

apiVersion: v1
kind: Service
metadata:
  name: node-frontend-service
  namespace: frontend-ns
spec:
  selector:
    app: node-frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000

  type: LoadBalancer
