apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontend.name }}-service
  namespace: {{ .Values.frontend.namespace }}
  labels:
{{- toYaml .Values.frontend.labels | nindent 4 }}
spec:
  selector:
    app: {{ .Values.frontend.labels.app }}
  ports:
    - protocol: TCP
      port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.containerPort }}
  type: {{ .Values.frontend.service.type }}
  